
---
- name: Setup Redis 
  hosts: server_role_redis_server
  become: true
  roles: 
    - server_role_redis_server

- name: Frontend Servers
  hosts: server_role_frontend_server
  become: true
  roles: 
    - server_role_frontend_server